# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    providers:
        app_users:
            ldap:
                service: app.ldap
                base_dn: dc=example,dc=com
                search_dn: OU=mathematicians,DC=example,DC=com
                search_password: password
#                filter: (sAMAccountName={username})
                filter: "(&(objectClass=user)(sAMAccountName={username}))"
                default_roles: ROLE_USER
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/login$
            anonymous: ~

        backend:
             provider: app_users
             pattern:  ^/admin
             logout:
                 path:   logout
                 target: login
             form_login_ldap:
                 service: app.ldap
                 dn_string: CN={username},OU=mathematicians,DC=example,DC=com
                 check_path: login_check
                 login_path: login
